###############################################################################
# AUTOGENERATED FILE
# Created by cment
# DO NOT EDIT DIRECTLY
# Best regenerated
###############################################################################
include(ExternalProject)
set(GLOBAL_OUTPUT_PATH ${PROJECT_BINARY_DIR}/bin)
set(CMAKE_INSTALL_PREFIX ${PROJECT_BINARY_DIR}/install)
# Sets global output directory for single configuration (GCC)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${GLOBAL_OUTPUT_PATH})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${GLOBAL_OUTPUT_PATH})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${GLOBAL_OUTPUT_PATH})
# Sets global output directory for sub-configurations (msvc, mingw)
foreach(OUTPUTCONFIG ${CMAKE_CONFIGURATION_TYPES})
    string(TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${OUTPUTCONFIG} ${GLOBAL_OUTPUT_PATH})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${OUTPUTCONFIG} ${GLOBAL_OUTPUT_PATH})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${OUTPUTCONFIG} ${GLOBAL_OUTPUT_PATH})
endforeach(OUTPUTCONFIG CMAKE_CONFIGURATION_TYPES)

###############################################################################
# ogdl-c 
###############################################################################
ExternalProject_Add(
    ogdl-c_External
    GIT_REPOSITORY "https://github.com/timlukins/ogdl-c"
    GIT_TAG "v1.0.1"
    UPDATE_COMMAND ""
    PATCH_COMMAND ""
    SOURCE_DIR "${CMAKE_SOURCE_DIR}/dep/ogdl-c"
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${GLOBAL_OUTPUT_PATH}/ogdl-c
    TEST_COMMAND ""
)
ExternalProject_Add_Step(
    ogdl-c_External CopyToBin
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${GLOBAL_OUTPUT_PATH}/ogdl-c/bin ${GLOBAL_OUTPUT_PATH}
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${GLOBAL_OUTPUT_PATH}/ogdl-c/lib ${GLOBAL_OUTPUT_PATH}
    DEPENDEES install
)
add_library(ogdl-c IMPORTED STATIC GLOBAL)
set_target_properties(ogdl-c PROPERTIES
        IMPORTED_LOCATION                 "${CMAKE_BINARY_DIR}/bin/ogdl-c/lib/libogdl.a")
add_dependencies(ogdl-c ogdl-c_External)

###############################################################################
# argparse
###############################################################################

ExternalProject_Add(
        argparse_External
        GIT_REPOSITORY "https://github.com/timlukins/argparse"
        GIT_TAG "1.0.1"
        UPDATE_COMMAND ""
        PATCH_COMMAND ""
        SOURCE_DIR "${CMAKE_SOURCE_DIR}/dep/argparse"
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${GLOBAL_OUTPUT_PATH}/argparse
        TEST_COMMAND ""
)
ExternalProject_Add_Step(
        argparse_External CopyToBin
        COMMAND ${CMAKE_COMMAND} -E copy_directory ${GLOBAL_OUTPUT_PATH}/argparse/bin ${GLOBAL_OUTPUT_PATH}
        COMMAND ${CMAKE_COMMAND} -E copy_directory ${GLOBAL_OUTPUT_PATH}/argparse/lib ${GLOBAL_OUTPUT_PATH}
        DEPENDEES install
)
add_library(argparse IMPORTED STATIC GLOBAL)
set_target_properties(argparse PROPERTIES
        IMPORTED_LOCATION                 "${CMAKE_BINARY_DIR}/bin/argparse/lib/libargparse.a")
add_dependencies(argparse argparse_External)

###############################################################################

include_directories(
        ${CMAKE_BINARY_DIR}/bin/ogdl-c/include
        ${CMAKE_BINARY_DIR}/bin/argparse/include
        )
target_link_libraries(${PROJECT_NAME} ogdl-c argparse)
add_dependencies(${PROJECT_NAME} ogdl-c argparse)
