/*
 * cment - an absurdly simple dependency tool for cmake
 * (c) 2016 T.C. Lukins
 * See LICENCE.txt
 */

#include "ogdl.h"
#include "argparse.h"
#include <stdio.h>
#include <string.h>

char header[] = {"\
# AUTOGENERATED FILE                                                            \
# Created by cment                                                              \
# DO NOT EDIT DIRECTLY                                                          \
# Best regenerated                                                              \
include(ExternalProject)                                                        \
set(GLOBAL_OUTPUT_PATH ${PROJECT_BINARY_DIR}/bin)                               \
set(CMAKE_INSTALL_PREFIX ${PROJECT_BINARY_DIR}/install)                         \
# Sets global output directory for single configuration (GCC)                   \
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${GLOBAL_OUTPUT_PATH})                       \
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${GLOBAL_OUTPUT_PATH})                       \
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${GLOBAL_OUTPUT_PATH})                       \
# Sets global output directory for sub-configurations (msvc, mingw)             \
foreach(OUTPUTCONFIG ${CMAKE_CONFIGURATION_TYPES})                              \
    string(TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG)                                \
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${OUTPUTCONFIG} ${GLOBAL_OUTPUT_PATH})   \
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${OUTPUTCONFIG} ${GLOBAL_OUTPUT_PATH})   \
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${OUTPUTCONFIG} ${GLOBAL_OUTPUT_PATH})   \
endforeach(OUTPUTCONFIG CMAKE_CONFIGURATION_TYPES)                              \
"};

char dependency[] = {"\
############################################################################### \
# %s                                                                            \
############################################################################### \
ExternalProject_Add(                                                            \
%s_External                                                                     \
GIT_REPOSITORY \"%s\"                                                           \
GIT_TAG \"%s\"                                                                  \
UPDATE_COMMAND \"\"                                                             \
PATCH_COMMAND \"\"                                                              \
SOURCE_DIR \"${CMAKE_SOURCE_DIR}/dep/%s\"                                       \
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${GLOBAL_OUTPUT_PATH}/%s                      \
TEST_COMMAND \"\"                                                               \
)                                                                               \
ExternalProject_Add_Step(                                                       \
%s_External CopyToBin                                                           \
COMMAND ${CMAKE_COMMAND} -E copy_directory ${GLOBAL_OUTPUT_PATH}/%s/bin ${GLOBAL_OUTPUT_PATH} \
COMMAND ${CMAKE_COMMAND} -E copy_directory ${GLOBAL_OUTPUT_PATH}/%s/lib ${GLOBAL_OUTPUT_PATH} \
DEPENDEES install                                                               \
)                                                                               \
add_library(%s IMPORTED STATIC GLOBAL)                                          \
set_target_properties(%s PROPERTIES                                             \
IMPORTED_LOCATION \"${CMAKE_BINARY_DIR}/bin/ogdl-c/lib/libogdl.a\")             \
add_dependencies(ogdl-c ogdl-c_External)                                        \
include_directories(${CMAKE_BINARY_DIR}/bin/ogdl-c/include)                     \
target_link_libraries(${PROJECT_NAME} ogdl-c)                                   \
"};

char footer[] = {"\
add_dependencies(${PROJECT_NAME} ogdl-c)                                        \
"};


int main(int argc, char **argv)
{
    char *path, rootstr[128];
    Graph g;
    FILE *f = stdin;
    OgdlParser parser;
    int index=1, maxLevel=-1, indent=2, root=0;

    if (argc==1) {
        puts("cment");
        puts("usage \\\n  cment [-d depth] [-n indent] [-r] <path> [file]");
        puts("version " VERSION);
        exit(1);
    }

    while (1) {
      if (!strncmp(argv[index],"-d",2)) {
        maxLevel = atoi(argv[index+1]);
        argc-=2;
        index+=2;
      }
      else if (!strncmp(argv[index],"-n",2)) {
        indent = atoi(argv[index+1]);
        argc-=2;
        index+=2;
        if (indent == 0) indent = 1;
      }
      else if (!strcmp(argv[index],"-r")) {   
        argc--;
        index++;
        root = 1;
      }
      else 
        break;
    }
    // first non option is path (mandatory)
    path = argv[index++];
    argc--;

    if (argc > 1) {
        f = fopen(argv[index],"r");
        if (!f) {
            printf ("File %s not found\n",argv[index]);
            exit(1);
        }
        /* set the root text to the file name */
        //fbasename(rootstr,argv[index]);
    }
    //else
    strcpy(rootstr,"root");
   
    parser = OgdlParser_new();
    OgdlParser_parse(parser,f);
    fclose(f); 

    if (! parser->g || ! parser->g[0]) 
        exit(1);
    g = parser->g[0];

    Graph_setName(g,rootstr);

    if (strcmp(".",path)) 
         g = Graph_get(g,path);

    if (g) {
        if (root) 
            Graph_fprint(g,stdout,maxLevel,indent,0);
        else if (g->size == 0 )
            printf("%s",g->name);
        else if (g->size == 1 && !g->nodes[0]->size)
            printf("%s",g->nodes[0]->name);
        else
            Graph_fprint(g,stdout,maxLevel,indent,1);
    }

    OgdlParser_free(parser);
    exit(g?0:1);
}

